"""Anti-Swing Strategy - Counter-trend mean reversion after extreme moves."""
from __future__ import annotations

import pandas as pd
import numpy as np
from dataclasses import dataclass
from typing import Dict, List, Optional

from src.features.linda.momentum import (
    rsi2_extreme_signals,
    stochastic_crossover_signals,
    validate_anti_swing_conditions,
    calculate_stochastic
)
from src.features.linda.moving_averages import calculate_sma
from src.config import get_linda_strategy_config


@dataclass
class AntiSwingSignal:
    """Signal generated by Anti-Swing strategy."""
    symbol: str
    timestamp: pd.Timestamp
    direction: str  # 'long' or 'short'
    entry_price: float
    stop_loss: float
    target_price: float
    confidence: float
    rsi2_value: float
    days_extreme: int
    target_ma: float
    strong_move_percent: float


class AntiSwingStrategy:
    """
    Anti-Swing Strategy Implementation.

    Counter-trend move after 2-3 days of strong directional movement:
    1. 2-day RSI < 10 (for longs) or RSI > 90 (for shorts)
    2. After 2-3 days of strong directional move
    3. Stochastic %K crosses above %D (longs) or below %D (shorts)
    4. Target: Return to 5-period moving average
    """

    def __init__(self, config: Optional[Dict] = None):
        self.config = config or get_linda_strategy_config('anti_swing').parameters
        self.name = "Anti-Swing"

        # Strategy parameters
        self.rsi2_period = self.config.get('rsi2_period', 2)
        self.rsi2_oversold = self.config.get('rsi2_oversold', 10)
        self.rsi2_overbought = self.config.get('rsi2_overbought', 90)
        self.stoch_k_period = self.config.get('stoch_k_period', 14)
        self.stoch_d_period = self.config.get('stoch_d_period', 3)
        self.min_extreme_days = self.config.get('min_extreme_days', 2)
        self.target_ma_period = self.config.get('target_ma_period', 5)
        self.strong_move_days = self.config.get('strong_move_days', 3)
        self.strong_move_threshold = self.config.get('strong_move_threshold', 0.05)  # 5%

    def analyze(self, data: pd.DataFrame) -> pd.DataFrame:
        """
        Analyze data for Anti-Swing setups.

        Args:
            data: OHLCV DataFrame with columns [open, high, low, close, volume]

        Returns:
            DataFrame with Anti-Swing analysis and signals
        """
        required_length = max(
            self.stoch_k_period + self.stoch_d_period,
            self.target_ma_period,
            self.strong_move_days
        ) + 10

        if len(data) < required_length:
            return pd.DataFrame()

        result = data.copy()

        # Calculate RSI2 extreme conditions
        rsi2_data = rsi2_extreme_signals(
            data['close'],
            oversold_threshold=self.rsi2_oversold,
            overbought_threshold=self.rsi2_overbought
        )
        result = result.join(rsi2_data)

        # Calculate Stochastic oscillator
        stoch_k, stoch_d = calculate_stochastic(
            data['high'], data['low'], data['close'],
            k_period=self.stoch_k_period,
            d_period=self.stoch_d_period
        )
        result['stoch_k'] = stoch_k
        result['stoch_d'] = stoch_d

        # Get stochastic crossover signals
        stoch_signals = stochastic_crossover_signals(stoch_k, stoch_d)
        result = result.join(stoch_signals, rsuffix='_stoch')

        # Calculate target moving average
        result['target_ma'] = calculate_sma(data['close'], self.target_ma_period)

        # Validate strong move conditions
        strong_move_data = validate_anti_swing_conditions(
            data['close'], data['high'], data['low'],
            strong_move_days=self.strong_move_days,
            strong_move_threshold=self.strong_move_threshold
        )
        result = result.join(strong_move_data)

        # Calculate additional mean reversion signals
        mean_reversion_data = self._calculate_mean_reversion_signals(data, result)
        result = result.join(mean_reversion_data)

        # Generate Anti-Swing signals
        signals = self._generate_signals(data, result)
        result = result.join(signals)

        return result

    def _calculate_mean_reversion_signals(self, data: pd.DataFrame, analysis: pd.DataFrame) -> pd.DataFrame:
        """Calculate additional mean reversion signals."""
        result = pd.DataFrame(index=data.index)

        # Distance from moving averages
        result['distance_from_ma5'] = (data['close'] - analysis['target_ma']) / analysis['target_ma'] * 100
        result['distance_from_ma20'] = (data['close'] - data['close'].rolling(20).mean()) / data['close'].rolling(20).mean() * 100

        # Bollinger Band position
        bb_period = 20
        bb_std = 2
        bb_middle = data['close'].rolling(bb_period).mean()
        bb_std_dev = data['close'].rolling(bb_period).std()
        bb_upper = bb_middle + (bb_std_dev * bb_std)
        bb_lower = bb_middle - (bb_std_dev * bb_std)

        result['bb_position'] = (data['close'] - bb_lower) / (bb_upper - bb_lower)
        result['bb_oversold'] = result['bb_position'] < 0.1   # Below 10% of BB range
        result['bb_overbought'] = result['bb_position'] > 0.9  # Above 90% of BB range

        # Price velocity (rate of change)
        result['velocity_3d'] = data['close'].pct_change(3)
        result['velocity_5d'] = data['close'].pct_change(5)

        # Extreme velocity conditions
        result['extreme_down_velocity'] = result['velocity_3d'] < -0.10  # > 10% decline in 3 days
        result['extreme_up_velocity'] = result['velocity_3d'] > 0.10     # > 10% gain in 3 days

        return result

    def _generate_signals(self, data: pd.DataFrame, analysis: pd.DataFrame) -> pd.DataFrame:
        """Generate Anti-Swing entry signals."""
        signals = pd.DataFrame(index=data.index)

        # Initialize signal columns
        signals['as_long_setup'] = False
        signals['as_short_setup'] = False
        signals['as_long_entry'] = False
        signals['as_short_entry'] = False
        signals['as_confidence'] = 0.0
        signals['as_stop_loss'] = np.nan
        signals['as_target'] = np.nan

        # Setup conditions - combine multiple criteria
        # Long setup: oversold after strong decline
        long_setup_conditions = (
            analysis['rsi2_oversold'] &                    # RSI2 < 10
            analysis['valid_anti_swing_long'] &            # Strong decline + RSI extreme
            (analysis['oversold_days'] >= self.min_extreme_days) &  # Multiple days oversold
            (analysis.get('bb_oversold', False) |
             analysis.get('extreme_down_velocity', False))  # Additional oversold confirmation
        )

        # Short setup: overbought after strong rally
        short_setup_conditions = (
            analysis['rsi2_overbought'] &                  # RSI2 > 90
            analysis['valid_anti_swing_short'] &           # Strong rally + RSI extreme
            (analysis['overbought_days'] >= self.min_extreme_days) &  # Multiple days overbought
            (analysis.get('bb_overbought', False) |
             analysis.get('extreme_up_velocity', False))   # Additional overbought confirmation
        )

        signals['as_long_setup'] = long_setup_conditions
        signals['as_short_setup'] = short_setup_conditions

        # Entry conditions - stochastic confirmation
        for i in range(1, len(data)):
            # Long entry: setup + stochastic bullish crossover
            if (signals['as_long_setup'].iloc[i] and
                analysis['quality_long_signal_stoch'].iloc[i]):

                signals['as_long_entry'].iloc[i] = True
                signals['as_stop_loss'].iloc[i] = self._calculate_long_stop(data, analysis, i)
                signals['as_target'].iloc[i] = self._calculate_long_target(data, analysis, i)
                signals['as_confidence'].iloc[i] = self._calculate_confidence(data, analysis, i, 'long')

            # Short entry: setup + stochastic bearish crossover
            elif (signals['as_short_setup'].iloc[i] and
                  analysis['quality_short_signal_stoch'].iloc[i]):

                signals['as_short_entry'].iloc[i] = True
                signals['as_stop_loss'].iloc[i] = self._calculate_short_stop(data, analysis, i)
                signals['as_target'].iloc[i] = self._calculate_short_target(data, analysis, i)
                signals['as_confidence'].iloc[i] = self._calculate_confidence(data, analysis, i, 'short')

        return signals

    def _calculate_long_stop(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate stop loss for long position."""
        # Use recent swing low or percentage stop
        lookback = 5
        start_idx = max(0, index - lookback)

        # Recent swing low
        swing_low = data['low'].iloc[start_idx:index+1].min()

        # Percentage stop (conservative for mean reversion)
        percentage_stop = data['close'].iloc[index] * 0.95  # 5% stop

        # Use the more conservative (higher) stop
        stop_loss = max(swing_low * 0.98, percentage_stop)  # 2% buffer below swing low

        return stop_loss

    def _calculate_short_stop(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate stop loss for short position."""
        # Use recent swing high or percentage stop
        lookback = 5
        start_idx = max(0, index - lookback)

        # Recent swing high
        swing_high = data['high'].iloc[start_idx:index+1].max()

        # Percentage stop (conservative for mean reversion)
        percentage_stop = data['close'].iloc[index] * 1.05  # 5% stop

        # Use the more conservative (lower) stop
        stop_loss = min(swing_high * 1.02, percentage_stop)  # 2% buffer above swing high

        return stop_loss

    def _calculate_long_target(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate profit target for long position."""
        # Primary target: 5-period moving average
        ma_target = analysis['target_ma'].iloc[index]

        # Alternative targets
        entry_price = data['close'].iloc[index]

        # 50% retracement of recent decline
        lookback = self.strong_move_days + 2
        start_idx = max(0, index - lookback)
        recent_high = data['high'].iloc[start_idx:index].max()
        recent_low = data['low'].iloc[start_idx:index+1].min()
        retracement_target = recent_low + ((recent_high - recent_low) * 0.5)

        # Use the closest reasonable target
        if not pd.isna(ma_target) and ma_target > entry_price:
            # If MA is above current price, use it
            target = ma_target
        else:
            # Otherwise use retracement target
            target = max(retracement_target, entry_price * 1.02)  # At least 2% gain

        return target

    def _calculate_short_target(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate profit target for short position."""
        # Primary target: 5-period moving average
        ma_target = analysis['target_ma'].iloc[index]

        # Alternative targets
        entry_price = data['close'].iloc[index]

        # 50% retracement of recent rally
        lookback = self.strong_move_days + 2
        start_idx = max(0, index - lookback)
        recent_high = data['high'].iloc[start_idx:index+1].max()
        recent_low = data['low'].iloc[start_idx:index].min()
        retracement_target = recent_high - ((recent_high - recent_low) * 0.5)

        # Use the closest reasonable target
        if not pd.isna(ma_target) and ma_target < entry_price:
            # If MA is below current price, use it
            target = ma_target
        else:
            # Otherwise use retracement target
            target = min(retracement_target, entry_price * 0.98)  # At least 2% gain

        return target

    def _calculate_confidence(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int, direction: str) -> float:
        """Calculate confidence score for the signal."""
        confidence = 0.0

        # Base confidence for meeting criteria
        confidence += 0.4

        # RSI2 extremeness bonus
        rsi2_value = analysis['rsi2'].iloc[index]
        if direction == 'long':
            if rsi2_value < 5:
                confidence += 0.2
            elif rsi2_value < 8:
                confidence += 0.1
        else:  # short
            if rsi2_value > 95:
                confidence += 0.2
            elif rsi2_value > 92:
                confidence += 0.1

        # Days in extreme territory bonus
        if direction == 'long':
            extreme_days = analysis['oversold_days'].iloc[index]
        else:
            extreme_days = analysis['overbought_days'].iloc[index]

        if extreme_days >= 3:
            confidence += 0.15
        elif extreme_days >= 2:
            confidence += 0.1

        # Strong move magnitude bonus
        if direction == 'long':
            move_percent = abs(analysis.get('velocity_3d', 0).iloc[index])
        else:
            move_percent = abs(analysis.get('velocity_3d', 0).iloc[index])

        if move_percent > 0.15:  # > 15% move
            confidence += 0.1
        elif move_percent > 0.10:  # > 10% move
            confidence += 0.05

        # Bollinger Band extreme bonus
        if direction == 'long' and analysis.get('bb_oversold', False).iloc[index]:
            confidence += 0.1
        elif direction == 'short' and analysis.get('bb_overbought', False).iloc[index]:
            confidence += 0.1

        # Distance from MA bonus (further from MA = better mean reversion opportunity)
        distance_from_ma = abs(analysis.get('distance_from_ma5', 0).iloc[index])
        if distance_from_ma > 8:  # > 8% from MA
            confidence += 0.05

        return min(confidence, 1.0)

    def get_signals(self, data: pd.DataFrame) -> List[AntiSwingSignal]:
        """Get list of Anti-Swing signals from analyzed data."""
        analysis = self.analyze(data)
        signals = []

        for i, row in analysis.iterrows():
            if row.get('as_long_entry', False):
                signal = AntiSwingSignal(
                    symbol=getattr(data, 'symbol', 'UNKNOWN'),
                    timestamp=i,
                    direction='long',
                    entry_price=data.loc[i, 'close'],
                    stop_loss=row['as_stop_loss'],
                    target_price=row['as_target'],
                    confidence=row['as_confidence'],
                    rsi2_value=row.get('rsi2', 0),
                    days_extreme=int(row.get('oversold_days', 0)),
                    target_ma=row.get('target_ma', 0),
                    strong_move_percent=row.get('velocity_3d', 0) * 100
                )
                signals.append(signal)

            elif row.get('as_short_entry', False):
                signal = AntiSwingSignal(
                    symbol=getattr(data, 'symbol', 'UNKNOWN'),
                    timestamp=i,
                    direction='short',
                    entry_price=data.loc[i, 'close'],
                    stop_loss=row['as_stop_loss'],
                    target_price=row['as_target'],
                    confidence=row['as_confidence'],
                    rsi2_value=row.get('rsi2', 0),
                    days_extreme=int(row.get('overbought_days', 0)),
                    target_ma=row.get('target_ma', 0),
                    strong_move_percent=row.get('velocity_3d', 0) * 100
                )
                signals.append(signal)

        return signals

    def validate_market_timing(self, data: pd.DataFrame) -> pd.DataFrame:
        """Validate optimal timing for Anti-Swing strategy."""
        validation = pd.DataFrame(index=data.index)

        # Anti-swing works better in:
        # 1. Trending but not parabolic markets
        # 2. Markets with regular pullbacks/bounces
        # 3. Moderate volatility environments

        # Calculate trend strength but not too strong
        price_sma20 = data['close'].rolling(20).mean()
        price_sma50 = data['close'].rolling(50).mean()

        validation['trending_market'] = (
            ((price_sma20 > price_sma50) & (price_sma20.diff() > 0)) |  # Uptrend
            ((price_sma20 < price_sma50) & (price_sma20.diff() < 0))    # Downtrend
        )

        # Not parabolic (price not too far from moving average)
        distance_from_trend = abs((data['close'] - price_sma20) / price_sma20)
        validation['not_parabolic'] = distance_from_trend < 0.15  # Within 15% of 20-day MA

        # Regular pullback pattern (look for oscillation)
        high_10 = data['high'].rolling(10).max()
        low_10 = data['low'].rolling(10).min()
        range_10 = high_10 - low_10
        recent_range = data['high'] - data['low']

        validation['healthy_pullbacks'] = recent_range > (range_10 * 0.3)  # Recent range is significant

        # Volatility in good range
        returns = data['close'].pct_change()
        volatility = returns.rolling(20).std() * np.sqrt(252)
        validation['good_volatility'] = (volatility > 0.20) & (volatility < 0.50)  # 20-50% annual

        # Overall timing score
        validation['anti_swing_timing'] = (
            validation['trending_market'] &
            validation['not_parabolic'] &
            validation['healthy_pullbacks'] &
            validation['good_volatility']
        )

        return validation