"""Holy Grail Setup Strategy - Linda Raschke's signature pattern."""
from __future__ import annotations

import pandas as pd
import numpy as np
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

from src.features.linda.adx_system import linda_adx_strategy_signals
from src.features.linda.momentum import momentum_divergence, calculate_rsi
from src.config import get_linda_strategy_config


@dataclass
class HolyGrailSignal:
    """Signal generated by Holy Grail strategy."""
    symbol: str
    timestamp: pd.Timestamp
    direction: str  # 'long' or 'short'
    entry_price: float
    stop_loss: float
    target_price: float
    confidence: float
    setup_type: str
    adx_value: float
    pullback_bars: int
    rsi_value: float


class HolyGrailStrategy:
    """
    Holy Grail Setup Strategy Implementation.

    Linda Raschke's signature pattern:
    1. Strong trend (ADX > 30)
    2. 3-5 bar pullback in trending market
    3. Momentum divergence (RSI oversold/overbought)
    4. Entry on break of pullback high/low
    """

    def __init__(self, config: Optional[Dict] = None):
        self.config = config or get_linda_strategy_config('holy_grail').parameters
        self.name = "Holy Grail"

        # Strategy parameters
        self.adx_period = self.config.get('adx_period', 14)
        self.adx_strong_threshold = self.config.get('adx_strong_threshold', 30.0)
        self.adx_weak_threshold = self.config.get('adx_weak_threshold', 20.0)
        self.pullback_min_bars = self.config.get('pullback_min_bars', 3)
        self.pullback_max_bars = self.config.get('pullback_max_bars', 5)
        self.rsi_period = self.config.get('rsi_period', 14)
        self.rsi_oversold = self.config.get('rsi_oversold', 30)
        self.rsi_overbought = self.config.get('rsi_overbought', 70)
        self.entry_confirmation_required = self.config.get('entry_confirmation_required', True)

    def analyze(self, data: pd.DataFrame) -> pd.DataFrame:
        """
        Analyze data for Holy Grail setups.

        Args:
            data: OHLCV DataFrame with columns [open, high, low, close, volume]

        Returns:
            DataFrame with Holy Grail analysis and signals
        """
        if len(data) < max(self.adx_period, self.rsi_period) + self.pullback_max_bars:
            return pd.DataFrame()

        result = data.copy()

        # Calculate ADX system signals
        adx_signals = linda_adx_strategy_signals(
            data['high'], data['low'], data['close'],
            adx_period=self.adx_period,
            strong_adx_threshold=self.adx_strong_threshold,
            weak_adx_threshold=self.adx_weak_threshold
        )

        # Calculate RSI
        rsi = calculate_rsi(data['close'], self.rsi_period)

        # Add indicators to result
        for col in adx_signals.columns:
            result[f'adx_{col}'] = adx_signals[col]
        result['rsi'] = rsi

        # Detect pullbacks
        pullback_data = self._detect_pullbacks(data, adx_signals)
        result = result.join(pullback_data)

        # Detect momentum divergence
        divergence_data = momentum_divergence(data['close'], rsi)
        result = result.join(divergence_data, rsuffix='_divergence')

        # Generate Holy Grail signals
        hg_signals = self._generate_signals(data, result)
        result = result.join(hg_signals)

        return result

    def _detect_pullbacks(self, data: pd.DataFrame, adx_data: pd.DataFrame) -> pd.DataFrame:
        """Detect pullback patterns in trending markets."""
        result = pd.DataFrame(index=data.index)

        # Strong trend requirement
        strong_trend = adx_data['trend_strong']
        uptrend = adx_data['bullish_bias']
        downtrend = adx_data['bearish_bias']

        # Calculate price swings
        highs = data['high']
        lows = data['low']

        # Detect pullback patterns for different bar counts
        for bars in range(self.pullback_min_bars, self.pullback_max_bars + 1):
            # For uptrends: look for pullbacks (lower highs/lows)
            uptrend_pullback = self._detect_uptrend_pullback(highs, lows, bars)
            # For downtrends: look for pullbacks (higher highs/lows)
            downtrend_pullback = self._detect_downtrend_pullback(highs, lows, bars)

            result[f'uptrend_pullback_{bars}'] = strong_trend & uptrend & uptrend_pullback
            result[f'downtrend_pullback_{bars}'] = strong_trend & downtrend & downtrend_pullback

        # Overall pullback detection
        uptrend_pullback_cols = [col for col in result.columns if 'uptrend_pullback_' in col]
        downtrend_pullback_cols = [col for col in result.columns if 'downtrend_pullback_' in col]

        result['uptrend_pullback'] = result[uptrend_pullback_cols].any(axis=1)
        result['downtrend_pullback'] = result[downtrend_pullback_cols].any(axis=1)
        result['any_pullback'] = result['uptrend_pullback'] | result['downtrend_pullback']

        # Pullback depth analysis
        result['pullback_depth'] = self._calculate_pullback_depth(data, result)

        return result

    def _detect_uptrend_pullback(self, highs: pd.Series, lows: pd.Series, bars: int) -> pd.Series:
        """Detect pullback in uptrend (series of lower highs and/or lower lows)."""
        pullback = pd.Series(False, index=highs.index)

        for i in range(bars, len(highs)):
            # Check if we have consecutive lower highs
            lower_highs = True
            for j in range(1, bars):
                if highs.iloc[i - j] >= highs.iloc[i - j - 1]:
                    lower_highs = False
                    break

            # Check if recent high is lower than high before pullback started
            if lower_highs and i >= bars + 1:
                recent_high = highs.iloc[i - bars + 1:i + 1].max()
                prior_high = highs.iloc[i - bars - 1]
                pullback.iloc[i] = recent_high < prior_high

        return pullback

    def _detect_downtrend_pullback(self, highs: pd.Series, lows: pd.Series, bars: int) -> pd.Series:
        """Detect pullback in downtrend (series of higher lows and/or higher highs)."""
        pullback = pd.Series(False, index=lows.index)

        for i in range(bars, len(lows)):
            # Check if we have consecutive higher lows
            higher_lows = True
            for j in range(1, bars):
                if lows.iloc[i - j] <= lows.iloc[i - j - 1]:
                    higher_lows = False
                    break

            # Check if recent low is higher than low before pullback started
            if higher_lows and i >= bars + 1:
                recent_low = lows.iloc[i - bars + 1:i + 1].min()
                prior_low = lows.iloc[i - bars - 1]
                pullback.iloc[i] = recent_low > prior_low

        return pullback

    def _calculate_pullback_depth(self, data: pd.DataFrame, pullback_data: pd.DataFrame) -> pd.Series:
        """Calculate the depth of pullbacks as percentage of recent range."""
        depth = pd.Series(0.0, index=data.index)

        lookback = max(self.pullback_max_bars + 2, 10)

        for i in range(lookback, len(data)):
            if pullback_data['any_pullback'].iloc[i]:
                # Calculate pullback depth
                recent_range = data['high'].iloc[i-lookback:i].max() - data['low'].iloc[i-lookback:i].min()
                if recent_range > 0:
                    if pullback_data['uptrend_pullback'].iloc[i]:
                        pullback_move = data['high'].iloc[i-lookback:i].max() - data['low'].iloc[i]
                    else:
                        pullback_move = data['high'].iloc[i] - data['low'].iloc[i-lookback:i].min()

                    depth.iloc[i] = pullback_move / recent_range

        return depth

    def _generate_signals(self, data: pd.DataFrame, analysis: pd.DataFrame) -> pd.DataFrame:
        """Generate Holy Grail entry signals."""
        signals = pd.DataFrame(index=data.index)

        # Initialize signal columns
        signals['hg_long_setup'] = False
        signals['hg_short_setup'] = False
        signals['hg_long_entry'] = False
        signals['hg_short_entry'] = False
        signals['hg_confidence'] = 0.0
        signals['hg_stop_loss'] = np.nan
        signals['hg_target'] = np.nan

        # Setup conditions
        strong_trend = analysis['adx_trend_strong']
        uptrend = analysis['adx_bullish_bias']
        downtrend = analysis['adx_bearish_bias']

        # RSI momentum conditions
        rsi_oversold_pullback = (analysis['rsi'] < self.rsi_oversold) & analysis['uptrend_pullback']
        rsi_overbought_pullback = (analysis['rsi'] > self.rsi_overbought) & analysis['downtrend_pullback']

        # Divergence confirmation
        bullish_divergence = analysis.get('bullish_divergence', False)
        bearish_divergence = analysis.get('bearish_divergence', False)

        # Setup identification
        signals['hg_long_setup'] = (
            strong_trend &
            uptrend &
            analysis['uptrend_pullback'] &
            (rsi_oversold_pullback | bullish_divergence)
        )

        signals['hg_short_setup'] = (
            strong_trend &
            downtrend &
            analysis['downtrend_pullback'] &
            (rsi_overbought_pullback | bearish_divergence)
        )

        # Entry signals (break of pullback high/low)
        for i in range(1, len(data)):
            # Long entry: break above previous bar's high after setup
            if signals['hg_long_setup'].iloc[i-1] and data['high'].iloc[i] > data['high'].iloc[i-1]:
                signals['hg_long_entry'].iloc[i] = True
                signals['hg_stop_loss'].iloc[i] = self._calculate_long_stop(data, analysis, i)
                signals['hg_target'].iloc[i] = self._calculate_long_target(data, analysis, i)
                signals['hg_confidence'].iloc[i] = self._calculate_confidence(data, analysis, i, 'long')

            # Short entry: break below previous bar's low after setup
            if signals['hg_short_setup'].iloc[i-1] and data['low'].iloc[i] < data['low'].iloc[i-1]:
                signals['hg_short_entry'].iloc[i] = True
                signals['hg_stop_loss'].iloc[i] = self._calculate_short_stop(data, analysis, i)
                signals['hg_target'].iloc[i] = self._calculate_short_target(data, analysis, i)
                signals['hg_confidence'].iloc[i] = self._calculate_confidence(data, analysis, i, 'short')

        return signals

    def _calculate_long_stop(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate stop loss for long position."""
        # Use pullback low or support level
        lookback = self.pullback_max_bars + 2
        start_idx = max(0, index - lookback)

        # Find the lowest low during pullback
        pullback_low = data['low'].iloc[start_idx:index+1].min()

        # Add small buffer below the low
        atr = analysis.get('atr', pd.Series(0)).iloc[index]
        if pd.isna(atr) or atr == 0:
            atr = (data['high'] - data['low']).rolling(14).mean().iloc[index]

        stop_loss = pullback_low - (atr * 0.5)
        return stop_loss

    def _calculate_short_stop(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate stop loss for short position."""
        # Use pullback high or resistance level
        lookback = self.pullback_max_bars + 2
        start_idx = max(0, index - lookback)

        # Find the highest high during pullback
        pullback_high = data['high'].iloc[start_idx:index+1].max()

        # Add small buffer above the high
        atr = analysis.get('atr', pd.Series(0)).iloc[index]
        if pd.isna(atr) or atr == 0:
            atr = (data['high'] - data['low']).rolling(14).mean().iloc[index]

        stop_loss = pullback_high + (atr * 0.5)
        return stop_loss

    def _calculate_long_target(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate profit target for long position."""
        entry_price = data['high'].iloc[index]  # Break above previous high
        stop_loss = self._calculate_long_stop(data, analysis, index)

        # Risk-reward ratio of 2:1
        risk = entry_price - stop_loss
        target = entry_price + (risk * 2.0)

        return target

    def _calculate_short_target(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate profit target for short position."""
        entry_price = data['low'].iloc[index]  # Break below previous low
        stop_loss = self._calculate_short_stop(data, analysis, index)

        # Risk-reward ratio of 2:1
        risk = stop_loss - entry_price
        target = entry_price - (risk * 2.0)

        return target

    def _calculate_confidence(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int, direction: str) -> float:
        """Calculate confidence score for the signal."""
        confidence = 0.0

        # Base confidence for meeting basic criteria
        confidence += 0.4

        # ADX strength bonus
        adx_value = analysis.get('adx_adx', pd.Series(0)).iloc[index]
        if adx_value > 40:
            confidence += 0.2
        elif adx_value > 35:
            confidence += 0.1

        # Pullback depth bonus (moderate pullbacks are better)
        pullback_depth = analysis.get('pullback_depth', pd.Series(0)).iloc[index]
        if 0.3 <= pullback_depth <= 0.6:  # 30-60% pullback is ideal
            confidence += 0.2
        elif 0.2 <= pullback_depth <= 0.8:
            confidence += 0.1

        # Divergence bonus
        if direction == 'long' and analysis.get('bullish_divergence', pd.Series(False)).iloc[index]:
            confidence += 0.15
        elif direction == 'short' and analysis.get('bearish_divergence', pd.Series(False)).iloc[index]:
            confidence += 0.15

        # Volume confirmation bonus
        if 'volume' in data.columns:
            volume_ma = data['volume'].rolling(20).mean().iloc[index]
            if data['volume'].iloc[index] > volume_ma * 1.2:
                confidence += 0.05

        return min(confidence, 1.0)

    def get_signals(self, data: pd.DataFrame) -> List[HolyGrailSignal]:
        """Get list of Holy Grail signals from analyzed data."""
        analysis = self.analyze(data)
        signals = []

        for i, row in analysis.iterrows():
            if row.get('hg_long_entry', False):
                signal = HolyGrailSignal(
                    symbol=getattr(data, 'symbol', 'UNKNOWN'),
                    timestamp=i,
                    direction='long',
                    entry_price=data.loc[i, 'high'],
                    stop_loss=row['hg_stop_loss'],
                    target_price=row['hg_target'],
                    confidence=row['hg_confidence'],
                    setup_type='pullback_breakout',
                    adx_value=row.get('adx_adx', 0),
                    pullback_bars=self._count_pullback_bars(analysis, i),
                    rsi_value=row.get('rsi', 0)
                )
                signals.append(signal)

            elif row.get('hg_short_entry', False):
                signal = HolyGrailSignal(
                    symbol=getattr(data, 'symbol', 'UNKNOWN'),
                    timestamp=i,
                    direction='short',
                    entry_price=data.loc[i, 'low'],
                    stop_loss=row['hg_stop_loss'],
                    target_price=row['hg_target'],
                    confidence=row['hg_confidence'],
                    setup_type='pullback_breakout',
                    adx_value=row.get('adx_adx', 0),
                    pullback_bars=self._count_pullback_bars(analysis, i),
                    rsi_value=row.get('rsi', 0)
                )
                signals.append(signal)

        return signals

    def _count_pullback_bars(self, analysis: pd.DataFrame, index: int) -> int:
        """Count the number of bars in the pullback."""
        for bars in range(self.pullback_min_bars, self.pullback_max_bars + 1):
            if (analysis.get(f'uptrend_pullback_{bars}', pd.Series(False)).iloc[index] or
                analysis.get(f'downtrend_pullback_{bars}', pd.Series(False)).iloc[index]):
                return bars
        return 0