"""Turtle Soup Strategy - Fade false breakouts from 20-day highs/lows."""
from __future__ import annotations

import pandas as pd
import numpy as np
from dataclasses import dataclass
from typing import Dict, List, Optional

from src.config import get_linda_strategy_config


@dataclass
class TurtleSoupSignal:
    """Signal generated by Turtle Soup strategy."""
    symbol: str
    timestamp: pd.Timestamp
    direction: str  # 'long' or 'short'
    entry_price: float
    stop_loss: float
    target_price: float
    confidence: float
    breakout_level: float
    failed_breakout_high: float
    failed_breakout_low: float
    volume_confirmation: bool


class TurtleSoupStrategy:
    """
    Turtle Soup Strategy Implementation.

    Fade false breakouts from 20-day highs/lows:
    1. Price breaks above 20-day high but closes below it (failed breakout)
    2. Next day, short if price trades below previous day's low
    3. Reverse for longs: break below 20-day low, fail, then rally
    """

    def __init__(self, config: Optional[Dict] = None):
        self.config = config or get_linda_strategy_config('turtle_soup').parameters
        self.name = "Turtle Soup"

        # Strategy parameters
        self.lookback_period = self.config.get('lookback_period', 20)
        self.confirmation_required = self.config.get('confirmation_required', True)
        self.min_breakout_size = self.config.get('min_breakout_size', 0.005)  # 0.5%
        self.risk_multiplier = self.config.get('risk_multiplier', 1.0)
        self.volume_threshold = self.config.get('volume_threshold', 1.2)  # 120% of average

    def analyze(self, data: pd.DataFrame) -> pd.DataFrame:
        """
        Analyze data for Turtle Soup setups.

        Args:
            data: OHLCV DataFrame with columns [open, high, low, close, volume]

        Returns:
            DataFrame with Turtle Soup analysis and signals
        """
        if len(data) < self.lookback_period + 5:
            return pd.DataFrame()

        result = data.copy()

        # Calculate 20-day highs and lows
        result['high_20'] = data['high'].rolling(window=self.lookback_period).max()
        result['low_20'] = data['low'].rolling(window=self.lookback_period).min()

        # Detect breakout attempts
        breakout_data = self._detect_breakout_attempts(data, result)
        result = result.join(breakout_data)

        # Detect failed breakouts
        failed_breakout_data = self._detect_failed_breakouts(data, result)
        result = result.join(failed_breakout_data)

        # Generate Turtle Soup signals
        signals = self._generate_signals(data, result)
        result = result.join(signals)

        return result

    def _detect_breakout_attempts(self, data: pd.DataFrame, analysis: pd.DataFrame) -> pd.DataFrame:
        """Detect breakout attempts above/below 20-day levels."""
        result = pd.DataFrame(index=data.index)

        # Breakout above 20-day high
        result['breakout_high_attempt'] = (
            (data['high'] > analysis['high_20']) &
            (data['high'].shift(1) <= analysis['high_20'].shift(1))
        )

        # Breakout below 20-day low
        result['breakout_low_attempt'] = (
            (data['low'] < analysis['low_20']) &
            (data['low'].shift(1) >= analysis['low_20'].shift(1))
        )

        # Calculate breakout size (percentage above/below level)
        result['breakout_high_size'] = (data['high'] - analysis['high_20']) / analysis['high_20']
        result['breakout_low_size'] = (analysis['low_20'] - data['low']) / analysis['low_20']

        # Significant breakouts only
        result['significant_high_breakout'] = (
            result['breakout_high_attempt'] &
            (result['breakout_high_size'] >= self.min_breakout_size)
        )

        result['significant_low_breakout'] = (
            result['breakout_low_attempt'] &
            (result['breakout_low_size'] >= self.min_breakout_size)
        )

        # Volume analysis
        if 'volume' in data.columns:
            volume_ma = data['volume'].rolling(window=20).mean()
            result['volume_expansion'] = data['volume'] > volume_ma * self.volume_threshold
        else:
            result['volume_expansion'] = True

        return result

    def _detect_failed_breakouts(self, data: pd.DataFrame, analysis: pd.DataFrame) -> pd.DataFrame:
        """Detect failed breakouts (close back inside range after breaking out)."""
        result = pd.DataFrame(index=data.index)

        # Failed breakout above (close below 20-day high after breaking above)
        result['failed_high_breakout'] = (
            analysis['significant_high_breakout'] &
            (data['close'] < analysis['high_20'])
        )

        # Failed breakout below (close above 20-day low after breaking below)
        result['failed_low_breakout'] = (
            analysis['significant_low_breakout'] &
            (data['close'] > analysis['low_20'])
        )

        # Calculate the "trap" range for failed breakouts
        result['trap_high'] = np.where(
            result['failed_high_breakout'],
            data['high'],  # High of the failed breakout bar
            np.nan
        )

        result['trap_low'] = np.where(
            result['failed_low_breakout'],
            data['low'],   # Low of the failed breakout bar
            np.nan
        )

        # Forward fill the trap levels for use in next bar signals
        result['trap_high_level'] = result['trap_high'].fillna(method='ffill')
        result['trap_low_level'] = result['trap_low'].fillna(method='ffill')

        # Clear trap levels after a few bars to avoid stale signals
        for col in ['trap_high_level', 'trap_low_level']:
            # Only keep trap levels for 3 bars after the failed breakout
            mask = pd.Series(False, index=result.index)
            for i in range(1, 4):  # 1, 2, 3 bars after
                mask |= (
                    result['failed_high_breakout'].shift(i) |
                    result['failed_low_breakout'].shift(i)
                ).fillna(False)

            result[col] = np.where(mask, result[col], np.nan)

        return result

    def _generate_signals(self, data: pd.DataFrame, analysis: pd.DataFrame) -> pd.DataFrame:
        """Generate Turtle Soup entry signals."""
        signals = pd.DataFrame(index=data.index)

        # Initialize signal columns
        signals['ts_long_setup'] = False
        signals['ts_short_setup'] = False
        signals['ts_long_entry'] = False
        signals['ts_short_entry'] = False
        signals['ts_confidence'] = 0.0
        signals['ts_stop_loss'] = np.nan
        signals['ts_target'] = np.nan

        # Setup conditions (failed breakout occurred)
        signals['ts_short_setup'] = analysis['failed_high_breakout']
        signals['ts_long_setup'] = analysis['failed_low_breakout']

        # Entry conditions
        for i in range(1, len(data)):
            # Short entry: failed high breakout yesterday, today trades below yesterday's low
            if (analysis['failed_high_breakout'].iloc[i-1] and
                data['low'].iloc[i] < data['low'].iloc[i-1]):

                signals['ts_short_entry'].iloc[i] = True
                signals['ts_stop_loss'].iloc[i] = self._calculate_short_stop(data, analysis, i)
                signals['ts_target'].iloc[i] = self._calculate_short_target(data, analysis, i)
                signals['ts_confidence'].iloc[i] = self._calculate_confidence(data, analysis, i, 'short')

            # Long entry: failed low breakout yesterday, today trades above yesterday's high
            if (analysis['failed_low_breakout'].iloc[i-1] and
                data['high'].iloc[i] > data['high'].iloc[i-1]):

                signals['ts_long_entry'].iloc[i] = True
                signals['ts_stop_loss'].iloc[i] = self._calculate_long_stop(data, analysis, i)
                signals['ts_target'].iloc[i] = self._calculate_long_target(data, analysis, i)
                signals['ts_confidence'].iloc[i] = self._calculate_confidence(data, analysis, i, 'long')

        return signals

    def _calculate_short_stop(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate stop loss for short position."""
        # Stop above the failed breakout high
        trap_high = analysis.get('trap_high_level', pd.Series(np.nan)).iloc[index-1]

        if pd.isna(trap_high):
            # Fallback: use recent high
            trap_high = data['high'].iloc[index-2:index].max()

        # Add small buffer above the trap high
        range_size = data['high'].iloc[index-1] - data['low'].iloc[index-1]
        buffer = range_size * 0.1  # 10% of previous bar's range

        return trap_high + buffer

    def _calculate_long_stop(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate stop loss for long position."""
        # Stop below the failed breakout low
        trap_low = analysis.get('trap_low_level', pd.Series(np.nan)).iloc[index-1]

        if pd.isna(trap_low):
            # Fallback: use recent low
            trap_low = data['low'].iloc[index-2:index].min()

        # Add small buffer below the trap low
        range_size = data['high'].iloc[index-1] - data['low'].iloc[index-1]
        buffer = range_size * 0.1  # 10% of previous bar's range

        return trap_low - buffer

    def _calculate_short_target(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate profit target for short position."""
        entry_price = data['low'].iloc[index-1]  # Entry below previous low
        stop_loss = self._calculate_short_stop(data, analysis, index)

        # Risk-reward ratio of 1.5:1 (conservative for counter-trend)
        risk = stop_loss - entry_price
        target = entry_price - (risk * 1.5)

        # Alternative target: 20-day low level
        low_20_target = analysis['low_20'].iloc[index]
        if not pd.isna(low_20_target):
            target = min(target, low_20_target)

        return target

    def _calculate_long_target(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int) -> float:
        """Calculate profit target for long position."""
        entry_price = data['high'].iloc[index-1]  # Entry above previous high
        stop_loss = self._calculate_long_stop(data, analysis, index)

        # Risk-reward ratio of 1.5:1 (conservative for counter-trend)
        risk = entry_price - stop_loss
        target = entry_price + (risk * 1.5)

        # Alternative target: 20-day high level
        high_20_target = analysis['high_20'].iloc[index]
        if not pd.isna(high_20_target):
            target = max(target, high_20_target)

        return target

    def _calculate_confidence(self, data: pd.DataFrame, analysis: pd.DataFrame, index: int, direction: str) -> float:
        """Calculate confidence score for the signal."""
        confidence = 0.0

        # Base confidence for meeting basic criteria
        confidence += 0.5

        # Breakout size bonus (larger failed breakouts are better)
        if direction == 'short':
            breakout_size = analysis.get('breakout_high_size', pd.Series(0)).iloc[index-1]
        else:
            breakout_size = analysis.get('breakout_low_size', pd.Series(0)).iloc[index-1]

        if breakout_size > 0.02:  # > 2% breakout
            confidence += 0.2
        elif breakout_size > 0.01:  # > 1% breakout
            confidence += 0.1

        # Volume confirmation bonus
        volume_expansion = analysis.get('volume_expansion', pd.Series(False)).iloc[index-1]
        if volume_expansion:
            confidence += 0.15

        # Time of failure bonus (quick failure is better)
        # If failed on the same day as breakout, higher confidence
        if index >= 1:
            same_day_failure = (
                analysis.get('significant_high_breakout', pd.Series(False)).iloc[index-1] or
                analysis.get('significant_low_breakout', pd.Series(False)).iloc[index-1]
            )
            if same_day_failure:
                confidence += 0.1

        # Market structure bonus (breaking below/above recent support/resistance)
        if direction == 'short':
            # Look for break below recent support
            recent_support = data['low'].iloc[index-5:index-1].min()
            if data['low'].iloc[index] < recent_support:
                confidence += 0.05

        else:  # long
            # Look for break above recent resistance
            recent_resistance = data['high'].iloc[index-5:index-1].max()
            if data['high'].iloc[index] > recent_resistance:
                confidence += 0.05

        return min(confidence, 1.0)

    def get_signals(self, data: pd.DataFrame) -> List[TurtleSoupSignal]:
        """Get list of Turtle Soup signals from analyzed data."""
        analysis = self.analyze(data)
        signals = []

        for i, row in analysis.iterrows():
            if row.get('ts_long_entry', False):
                signal = TurtleSoupSignal(
                    symbol=getattr(data, 'symbol', 'UNKNOWN'),
                    timestamp=i,
                    direction='long',
                    entry_price=data.loc[i-1, 'high'] if i > 0 else data.loc[i, 'high'],
                    stop_loss=row['ts_stop_loss'],
                    target_price=row['ts_target'],
                    confidence=row['ts_confidence'],
                    breakout_level=row.get('low_20', 0),
                    failed_breakout_high=data.loc[i-1, 'high'] if i > 0 else data.loc[i, 'high'],
                    failed_breakout_low=data.loc[i-1, 'low'] if i > 0 else data.loc[i, 'low'],
                    volume_confirmation=row.get('volume_expansion', False)
                )
                signals.append(signal)

            elif row.get('ts_short_entry', False):
                signal = TurtleSoupSignal(
                    symbol=getattr(data, 'symbol', 'UNKNOWN'),
                    timestamp=i,
                    direction='short',
                    entry_price=data.loc[i-1, 'low'] if i > 0 else data.loc[i, 'low'],
                    stop_loss=row['ts_stop_loss'],
                    target_price=row['ts_target'],
                    confidence=row['ts_confidence'],
                    breakout_level=row.get('high_20', 0),
                    failed_breakout_high=data.loc[i-1, 'high'] if i > 0 else data.loc[i, 'high'],
                    failed_breakout_low=data.loc[i-1, 'low'] if i > 0 else data.loc[i, 'low'],
                    volume_confirmation=row.get('volume_expansion', False)
                )
                signals.append(signal)

        return signals

    def validate_market_conditions(self, data: pd.DataFrame) -> pd.DataFrame:
        """Validate market conditions suitable for Turtle Soup strategy."""
        validation = pd.DataFrame(index=data.index)

        # Calculate volatility
        returns = data['close'].pct_change()
        volatility = returns.rolling(20).std() * np.sqrt(252)  # Annualized volatility

        # Turtle Soup works better in:
        # 1. Moderate to low volatility environments
        # 2. Range-bound or choppy markets
        # 3. When breakouts frequently fail

        validation['suitable_volatility'] = (volatility > 0.15) & (volatility < 0.35)  # 15-35% annual vol

        # Range-bound market detection
        high_20 = data['high'].rolling(20).max()
        low_20 = data['low'].rolling(20).min()
        range_size = (high_20 - low_20) / data['close']

        validation['range_bound_market'] = range_size < 0.25  # Range < 25% of price

        # Recent breakout failure rate
        breakout_attempts = (
            (data['high'] > data['high'].rolling(20).max().shift(1)) |
            (data['low'] < data['low'].rolling(20).min().shift(1))
        )

        # Count failed breakouts (close back inside range)
        failed_breakouts = (
            ((data['high'] > high_20.shift(1)) & (data['close'] < high_20.shift(1))) |
            ((data['low'] < low_20.shift(1)) & (data['close'] > low_20.shift(1)))
        )

        # Calculate failure rate over rolling window
        failure_rate = (failed_breakouts.rolling(20).sum() /
                       breakout_attempts.rolling(20).sum()).fillna(0)

        validation['high_failure_rate'] = failure_rate > 0.6  # > 60% failure rate

        # Overall suitability
        validation['turtle_soup_suitable'] = (
            validation['suitable_volatility'] &
            validation['range_bound_market'] &
            validation['high_failure_rate']
        )

        return validation